### PR TITLE
when ingesting all discovered LBs, report error, don't exit, if an LB does not have logging enabled

### PR DESCRIPTION
**Pull request by fernandrone**
If honeyelb/honeycloudfront was used with no arguments, it would try to ingest logs from all load balancers/distributions. However, if one of them had not logs enabled, it would terminate with a fatal
error. This made it very hard to have a single binary ingesting logs from all load balancers/distributions in an account, since every time a new lb/distro was created without logs it would break existing running daemons.

This commit fixes this by adding a check on the ingest logic. In case no positional argument is passed to honeyelb/honeycloudfront, it will NOT terminate the process if there is an error when
attempting to create a 'downloader' process for a lb/distro. Instead, a error-level log will be displayed. However, this means that it's technically possible for *all* lb/distros to fail and no logs to be ingested.

### CODE REVIEW

**Comment by fbcbarbosa** [comment]
Example, before:

```
time="2019-11-11T13:59:05Z" level=info msg="Access logs are enabled for CloudFront distribution ♥" bucket=5a-cloudfront-access-logs id=E3K<redacted>
time="2019-11-11T13:59:05Z" level=info msg="Attempting to ingest CloudFront distribution" id=E24<redacted>
time="2019-11-11T13:59:05Z" level=info msg="Getting recent objects" entity=E3K<redacted>prefix=ustasks/staging/E3K<redacted>.2019-11-11
Access logs are not configured for CloudFront distribution ID "E24<redacted>". Please enable them to use the ingest tool.

Access logs are not configured for CloudFront distribution ID "E24<redacted>". Please enable them to use the ingest tool.

For reference see this link:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html
```

Now:

```
time="2019-11-11T14:01:02Z" level=info msg="Bucket polling paused until the next set of logs are available" entity=EXN<redacted>
Access logs are not configured for CloudFront distribution ID "E24<redacted>". Please enable them to use the ingest tool.

For reference see this link:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html
time="2019-11-11T14:01:02Z" level=error msg="Could not ingest data from a distribution! See logs for more information." id=E24<redacted>
time="2019-11-11T14:01:02Z" level=info msg="Attempting to ingest CloudFront distribution" id=E25<redacted>
time="2019-11-11T14:01:02Z" level=info msg="Attempting to ingest CloudFront distribution" id=E25<redacted>
time="2019-11-11T14:01:02Z" level=info msg="Access logs are enabled for CloudFront distribution ♥" bucket=5a-cloudfront-access-logs id=E25<redacted>
```

**Comment by fbcbarbosa** [comment]
Some notes:

* I'm testing this in our infra, seems to work fine so far, but could always use more testing ^^
* Not sure if this breaks someone workflow... maybe someone _depends_ on this failing with an error when any lb/distro has no log enable? In this case maybe a flag would be preferable?https://xkcd.com/1172/

**Comment by nathanleclaire** [comment]
> Not sure if this breaks someone workflow... maybe someone depends on this failing with an error when any lb/distro has no log enable? In this case maybe a flag would be preferable?https://xkcd.com/1172/

heh... I suspect it's more just a dev oversight

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now because it's quite old and out of date. Feel free to re-open, if it’s still relevant.

**Pull request closed without merging**
