### PR TITLE
Bringing honeyaws up to date with our other go projects.

### PR DESCRIPTION
**Pull request by paulosman**
- Add dependabot.yml
- Use modern go modules, get rid of vendor dir and Gopkg files
- Minor code changes to bring up to date with API changes in libs

### CODE REVIEW

**Comment by vreynolds** [comment]
@paulosman is this going to be a patch/minor/major? can you apply a label

**Review by vreynolds — APPROVED** [review]
🧹

**Review by nathanleclaire — APPROVED** [review]
Satisfying. It has that new car smell.

**Comment by paulosman** [comment]
> @paulosman is this going to be a patch/minor/major? can you apply a label

labels coming next! This tool doesn't follow semver yet. When it does, we can release as a minor, I think - it's just packaging, not the interface.

**Pull request merged**
