### PR TITLE
Take config, envars, and .env

### PR DESCRIPTION
**Pull request by garthk**
* Take config from config file with `--config=config.ini`
* Take config from environment
* Take config from environment variables in `$PWD/.env`
    
Also:
    
* Configure the logger according to `Debug` option
* Ignore `.env` and `honeyelb` files
* Make the linter slightly happier

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Nice, thanks! I badly want a universal config file / standard for the various Honeycomb tools. Let me sync with the team what we might like to do and get back to you.

**Comment by garthk** [comment]
I'm all for a) standardising the configuration option names and environment variables across tools, and b) delaying the functionality to avoid making a breaking change to effect said standardisation. Onya.

**Comment by trondhindenes** [comment]
I came here looking for environment variable support, and was disappointed so see that it isn't implemented yet.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now as there has been no recent activity. Feel free to re-open if it’s still relevant.

**Pull request closed without merging**
